---
version: "3.3"
services:
  postgres_db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  migration:
    image: node
    depends_on: 
      - postgres_db
    volumes:
      - ./migrations:/src/migrations
      - ./lib:/src/lib
      - ./node_modules:/src/node_modules
    command: ["node", "/src/migrations/index.js"]