Resources:
    LyricService:
        Type: "AWS::Serverless::Function"
        Properties:
            Timeout: 10
            Handler: index.handler
            Runtime: nodejs12.x
            Environment:
                Variables:
                  DB_PORT:
                  DB_USER:
                  DB_HOST:
                  DB_PASSWORD:
                  DB_NAME:
            Events:
                Api:
                    Type: Api
                    Properties:
                        Path: /api/{proxy+}
                        Method: any