version: 2.1
orbs:
    aws-cli: circleci/aws-cli@1.2.1
    serverless-framework: circleci/serverless-framework@1.0.1
jobs:
    one:
        executor: serverless/default
        steps:
            - checkout
            - aws-cli/setup
            - serverless/setup
                app-name: serverless-framework-orb
                org-name: circleci
            - run: 
                command: sls deploy 
                name: deploy
workflows:
    one_and_two:
        jobs:
            - one