version: 2.1
jobs:
    build_dev:
        working_directory: ~/project
        docker:
            - image: buildpack-deps:xenial
        environment:
            DEPLOY_ENVIRONMENT: dev
        steps:
            - checkout
            - run:
                name: Setup Environment Variables
                command: |
                    echo 'export AWS_REST_API_ID="$AWS_DEV_REST_API_ID"' >> $BASH_ENV
                    echo 'export GIT_SHA="$(git rev-parse --short HEAD)"' >> $BASH_ENV
            # Better to create a docker image for this step
            - run:
                name: Install awscli, jq and npm
                command: |
                    apt-get update
                    apt-get install -y jq zip python3-pip
                    pip install --upgrade pip
                    pip3 install awscli
                    aws --version
                    curl -sL https://deb.nodesource.com/setup_12.x | bash -
                    apt-get install -y nodejs
                    npm install -g npm@latest
                    aws configure set default.region ${AWS_REGION}
            - run:
                name: Deploy Functions
                command: |
                    cd functions
                    ../.circleci/deploy.sh lyric-service    
workflows:
    full:
        jobs:
            - build_dev:
                filters:
                    branches:
                        only: master