version: 2.1
orbs:
    aws-cli: circleci/aws-cli@1.2.1
    serverless: circleci/serverless-framework@1.0.1
jobs:
    test:
        docker:
            - image: circleci/node:12
        steps:
            - attach_workspace:
                at: /tmp/workspace
            - checkout
            - run: npm ci
                name: Install Dependencies
            - run:
                name: Run Tests
                command: npm test
    deploy:
        executor: serverless/default
        steps:
            - checkout
            - aws-cli/setup
            - serverless/setup:
                app-name: serverless-framework-orb
                org-name: circleci
            - run: 
                command: sls deploy 
                name: Deploy
workflows:
    dev-release:
        jobs:
            - test
                name: dev-test
            - deploy
                name: dev-deploy
                requires:
                    - test