version: 2.1
jobs:        
    build_dev:
        docker:
            - image: "circleci/node:latest"
        steps:
            - checkout
            - run:
                name: Setup Environment Variables
                command: |
                    echo 'export AWS_REST_API_ID="$AWS_DEV_REST_API_ID"' >> $BASH_ENV
            - run:
                name: Install dependencies
                command: |
                    sudo apt-get update
                    sudo apt-get install -y jq zip python3-pip
            - run:
                name: Deploy functions
                command: |
                    cd functions
                    ../.circleci/deploy.sh build dev
workflows:
    full:
        jobs:
            - build_dev:
                filters:
                    branches:
                        only: master
