version: 2.1
orbs:
    aws-cli: circleci/aws-cli@1.2.1
    serverless: circleci/serverless-framework@1.0.1
    flyway: bwp-orbs/flyway@2.2.0
jobs:
    test:
        docker:
            - image: circleci/node:12
        steps:
            - attach_workspace:
                at: /tmp/workspace
            - checkout
            - run: 
                command: npm ci
                name: Install Dependencies
            - run:
                name: Run Tests
                command: npm test
    deploy:
        executor: serverless/default
        steps:
            - checkout
            - run: 
                command: npm ci
                name: Install Dependencies
            - aws-cli/setup
            - serverless/setup:
                app-name: serverless-framework-orb
                org-name: circleci
            - run: 
                command: sls deploy
                name: Deploy
            - run:
                name: Run migrations
                command: node migrations
workflows:
    dev-release:
        jobs:
            - test
            - deploy:
                requires:
                    - test                