FROM boxfuse/flyway:5.2.4-alpine

COPY ./database/migrations /flyway
COPY ./database/migrations/flyway.conf /flyway/conf/flyway.conf

VOLUME /flyway

ENV FLYWAY_CONNECT_RETRIES=20

CMD ["-X", "migrate"]
